GET http://localhost:8080/1_war/api/posts

###

POST http://localhost:8080/1_war/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

DELETE http://localhost:8080/1_war/api/posts/1

###

GET http://localhost:8080/1_war/api/posts/1

